[package]
name = "tray-indicator"
version = "0.1.0"
authors = ["Edwin Svensson <trayindicator@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libappindicator = "0.5" # Tray icon
gtk = "0.8"
# winapi = "0.3"
# macos?
